Portal Sisgen/Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Portal_Sisgen.Data;
using Portal_Sisgen.Models;
using Portal_Sisgen.Utility;

namespace Portal_Sisgen.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.AdminUser)]
    [Area("Admin")]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _db;

        public UserController(ApplicationDbContext db)
        {
            _db = db;
        }

        [Authorize(Roles = SD.AdminUser)]
        public async Task<IActionResult> Index()
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            return View(await _db.ApplicationUser.Where(u=>u.Id != claim.Value).ToListAsync());
        }



        //GET - EDIT
        [Authorize(Roles = SD.AdminUser)]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var applicationUser = await _db.ApplicationUser.FindAsync(id);
            if (applicationUser == null)
            {
                return NotFound();
            }

            return View(applicationUser);
        }

        //POST - EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = SD.AdminUser)]
        public async Task<IActionResult> Edit(ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
                var _userFromDb = await _db.ApplicationUser.FirstOrDefaultAsync(x => x.Id == applicationUser.Id);

                _userFromDb.Nombre = applicationUser.Nombre;
                _userFromDb.PhoneNumber = applicationUser.PhoneNumber;
                _userFromDb.Email = applicationUser.Email;

                _db.Update(_userFromDb);
                await _db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(applicationUser);
        }

        //GET - DELETE
        [Authorize(Roles = SD.AdminUser)]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var applicationUser = await _db.ApplicationUser.FindAsync(id);
            if (applicationUser == null)
            {
                return NotFound();
            }

            return View(applicationUser);
        }

        //POST - DELETE

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = SD.AdminUser)]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var applicationUser = await _db.ApplicationUser.FindAsync(id);

            if (applicationUser == null)
            {
                return NotFound();
            }
            _db.Remove(applicationUser);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


    }
}

Portal Sisgen/Areas/Client/Controllers/CesionesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Portal_Sisgen.Areas.User.Controllers
{
    [Area("Client")]
    public class CesionesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Portal Sisgen/Areas/Client/Controllers/ConsultarVentasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using Portal_Sisgen.Utility;

namespace Portal_Sisgen.Areas.User.Controllers
{
    [Area("Client")]
    public class ConsultarVentasController : Controller
    {
        //[HttpPost]
        //[ValidateAntiForgeryToken]

        public IActionResult Index()
        {
            //string query = "Select sis_contribuyente_id, dte_tipo,dte_folio,dte_fecha_emision,ID-ENVIO,dte_estado_sii,dte_acuse_recibo " +
            //    "From sis_bitacora ";

            //try
            //{
            //    using (MySqlConnection conexion = new MySqlConnection(SD.chain))
            //    {
            //        MySqlCommand cmd = new MySqlCommand(query);

            //        cmd.Connection = conexion;
            //        cmd.CommandType = CommandType.Text;
            //        conexion.Open();
            //        cmd.ExecuteNonQuery();

            //        MySqlDataAdapter da = new MySqlDataAdapter(cmd);
            //        DataTable dt = new DataTable();
            //        da.Fill(dt);

            //        foreach (DataRow dr in dt.Rows)
            //        {
            //            ViewData["response"] = "ID de su Contribuyente: " + dr["sis_contribuyente_id"].ToString();
            //        }
            //        conexion.Close();
            //    }

            //}
            //catch(Exception ex)
            //{
            //    ViewData["Error"] = ex.ToString();
            //}
            return View();
        }
    }
}

Portal Sisgen/Areas/Client/Controllers/LibroComprasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using Portal_Sisgen.Models;
using Portal_Sisgen.Utility;

namespace Portal_Sisgen.Areas.Client.Controllers
{
    [Area("Client")]
    public class LibroComprasController : Controller
    {
        public LibroComprasController()
        {
            /*
             *Comentarios del programador 
             Controlador creado para pruebas con mysql
             */
        }

        public IActionResult Index()
        {
            var query = "select * from libro_compra";
            var listaLibros = new List<LibroCompra>();
            try
            {
                using (MySqlConnection conexion = new MySqlConnection(SD.conexionMySql))
                {
                    var cmd = new MySqlCommand(query);
                    cmd.Connection = conexion;
                    cmd.CommandType = CommandType.Text;
                    conexion.Open();
                    cmd.ExecuteNonQuery();
                    MySqlDataAdapter da = new MySqlDataAdapter(cmd);
                    DataTable dt = new DataTable();
                    da.Fill(dt);

                    foreach (DataRow dr in dt.Rows)
                    {
                        LibroCompra _book = new LibroCompra();

                        _book.Libro_compra_ano = int.Parse(dr["libro_compra_ano"].ToString());
                        _book.Libro_compra_trackID = dr["libro_compra_trackid"].ToString();
                        listaLibros.Add(_book);
                    }


                    conexion.Close();
                }
            }
            catch (Exception)
            {
                throw;
            }

            return View(listaLibros);
        }
    }
}

Portal Sisgen/Views/Shared/_Layout.cshtml
@using Portal_Sisgen.Utility

<!DOCTYPE html>
<html lang="es-cl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"] - Portal Sisgen</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/AdminLTE.css" />
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

</head>

<body>
    <header>

        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-navy border-bottom box-shadow mb-3">
            <div class="container">

                <a class="navbar-brand" asp-area="Client" asp-controller="Home" asp-action="Index">Portal Sisgen</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />

                    <ul class="navbar-nav flex-grow-1 ">

                        <li class="nav-item">
                            <a class="nav-link " asp-area="Client" asp-controller="LibroCompras" asp-action="Index">
                                <i class="fas fa-search" style="color:darkorange"></i>
                                &nbsp;test
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link " asp-area="Client" asp-controller="Cesiones" asp-action="Index">
                                <i class="fas fa-money-check-alt" style="color:darkorange"></i>
                                &nbsp;Cesiones
                            </a>
                        </li>

                        <li class="nav-item dropdown text-white-50">
                            <a class="nav-link dropdown-toggle " href="#" id="navbarDropDownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-file-alt" style="color:darkorange"></i>
                                &nbsp;Mis DTE
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropDownMenuLink">
                                <a class="dropdown-item" asp-action="Index" asp-controller="ConsultarVentas" asp-area="Client">Consultar Ventas </a>
                                <a class="dropdown-item" asp-action="Index" asp-controller="ConsultarCompras" asp-area="Client">Consultar Compras</a>
                            </div>
                        </li>

                        @* REGISTRO DE CLIENTES SOLO SE VE EN LA CAPA ADMIN *@

                        @if (User.IsInRole(SD.AdminUser))
                        {
                            <li class="nav-item">
                                <a class="nav-link " asp-area="Admin" asp-controller="User" asp-action="Index">
                                    <i class="far fa-user" style="color:darkorange"></i>
                                    &nbsp;Usuarios
                                </a>
                            </li>
                        }
                    </ul>

                </div>

            </div>
        </nav>
    </header>

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    @*
        SOLUCIONAR PROBLEMA CON FOOTER PARA QUE NO SE SOBREPONGA EN LOS FORMULARIOS         
        <footer class="border-top pl-3 footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - Portal Sisgen - <a asp-area="" asp-controller="Home" asp-action="Privacy" >Privacidad</a>
        </div>
    </footer>*@


    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>

    <environment exclude="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Portal Sisgen/Views/Shared/_TableButtonPartial.cshtml
@model string

@* Esta es la paleta de botones que aparece en las tablas (Editar, Detalles,Eliminar) *@

<td style="width:150px">
    <div class="btn-group" role="group">

        <a class="btn btn-primary text-white" asp-action="Edit" asp-route-Id="@Model">
            <i class="fas fa-edit"></i>
        </a>
        &nbsp;
        @*<a class="btn btn-success text-white" asp-action="Details" asp-route-Id="@Model">
            <i class="fas fa-list-alt"></i>
        </a>*@

        <a class="btn btn-danger text-white" asp-action="Delete" asp-route-Id="@Model">
            <i class="fas fa-trash-alt"></i>
        </a>

    </div>
</td>